// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const backend = {
  "main": {
    "app": {
      /**
       * Call
       * @param {any} arg1 - Go Type: *menu.CallbackData
       * @returns {Promise} 
       */
      "Call": (arg1) => {
        return window.backend.main.app.Call(arg1);
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.backend.main.app.Greet(arg1);
      },
    }
  }

};
export default backend;
